#pragma config(Motor,  port1,           leftMotor,     tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           rightMotor,    tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port3,           liftMotor,     tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	//motor[leftMotor]  = 127;
	//wait1Msec(10000);

	while(1 == 1)
	{
		//motor[leftMotor] = vexRT[Ch3];
		//motor[rightMotor] = vexRT[Ch2];
	  motor[leftMotor]  = (vexRT[Ch3] - vexRT[Ch4])/2;  // (y + x)/2
    motor[rightMotor] = (vexRT[Ch3] + vexRT[Ch4])/2;  // (y - x)/2

    //motor[liftMotor] = vexRT[Ch2];

		if(vexRT[Btn5U] == 1)
		{
			motor[liftMotor] = 80;
		}
		else if(vexRT[Btn5D] == 1)
		{
			motor[liftMotor] = -80;
		}
		else
		{
			motor[liftMotor] = 10;
		}

		/*if(vexRT[Btn6U] == 1)
		{
			motor[clampMotor] = 80;
		}
		else if(vexRT[Btn6D] == 1)
		{
			motor[clampMotor] = -80;
		}
		else
		{
			motor[clampMotor] = 0;
		}
		if(vexRT[Ch1] > 0)
		{
			motor[leftMotor] = 127;
		}
		else
		{
			motor[leftMotor] = 0;
		}
		else if(vexRT[Btn6D] == 1)
		{
			motor[armMotor] = -40;
		}
		else
		{
			motor[armMotor] = 0;
		}*/
	}
}
